### 练习题 1：数组创建与属性查看



**题目：** 使用 `arange()` 函数创建一个从 1 到 12 的一维等差数组，然后使用 `reshape()` 方法将其重塑为 3行4列的二维数组 。请分别打印出该数组的维度（`ndim`）、形状（`shape`）和元素总个数（`size`）

In [1]:
import numpy as np

# 1. 使用arange()创建从1到12的一维等差数列数组
# 注意：arange是左闭右开区间，所以结束值写13才能包含12
arr_1d = np.arange(1, 13)
print("创建的一维数组：")
print(arr_1d)

# 2. 使用reshape()方法重塑为3行4列的二维数组
arr_2d = arr_1d.reshape(3, 4)
print("\n重塑后的3行4列二维数组：")
print(arr_2d)

# 3. 分别打印数组的维度、形状和元素总个数
print(f"\n数组的维度(ndim)：{arr_2d.ndim}")
print(f"数组的形状(shape)：{arr_2d.shape}")
print(f"数组的元素总个数(size)：{arr_2d.size}")

创建的一维数组：
[ 1  2  3  4  5  6  7  8  9 10 11 12]

重塑后的3行4列二维数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

数组的维度(ndim)：2
数组的形状(shape)：(3, 4)
数组的元素总个数(size)：12


### 练习题 2：数据类型转换



**题目：** 创建一个包含浮点数 `[1.5, 2.6, 3.7, 4.8]` 的 NumPy 数组。使用 `astype()` 方法将该数组的数据类型转换为 32位整数 (`np.int32`)，并打印转换前后的数组及其数据类型名称 (`dtype.name`) 。 

In [2]:
import numpy as np

# 1. 创建包含浮点数的NumPy数组
float_arr = np.array([1.5, 2.6, 3.7, 4.8])

# 2. 打印转换前的数组及其数据类型名称
print("转换前的数组：")
print(float_arr)
print(f"转换前的数据类型：{float_arr.dtype.name}")

# 3. 使用astype()方法转换为32位整数
int_arr = float_arr.astype(np.int32)

# 4. 打印转换后的数组及其数据类型名称
print("\n转换后的数组（小数部分被截断）：")
print(int_arr)
print(f"转换后的数据类型：{int_arr.dtype.name}")

转换前的数组：
[1.5 2.6 3.7 4.8]
转换前的数据类型：float64

转换后的数组（小数部分被截断）：
[1 2 3 4]
转换后的数据类型：int32


### 练习题 3：二维数组的切片操作



**题目：** 创建一个二维数组 `arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`。请使用切片操作获取原数组的前两行，以及第 2 到第 3 列的子数组（即期望得到 `[[2, 3], [6, 7]]`）。

In [3]:
import numpy as np

# 1. 创建题目指定的二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("原二维数组：")
print(arr)

# 2. 使用切片操作获取前两行、第2到第3列的子数组
# 语法：arr[行切片, 列切片]，切片遵循左闭右开原则
# 前两行：索引0和1 → :2
# 第2到第3列：索引1和2 → 1:3
sub_arr = arr[:2, 1:3]

# 3. 打印结果
print("\n提取的子数组（前两行，第2-3列）：")
print(sub_arr)

原二维数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

提取的子数组（前两行，第2-3列）：
[[2 3]
 [6 7]]


### 练习题 4：花式索引与布尔索引

**题目：** 给定一维数组 `arr = np.array([10, 15, 20, 25, 30, 35])`。

1. 使用花式索引提取第 1、3、5 个元素（即索引为 0, 2, 4 的元素）。  

   

   

2. 使用布尔索引提取数组中所有大于 20 的元素 。  


In [4]:
import numpy as np

# 1. 创建题目给定的一维数组
arr = np.array([10, 15, 20, 25, 30, 35])
print("原数组：")
print(arr)

# 2. 使用花式索引提取第1、3、5个元素（索引为0,2,4）
# 花式索引：传入整数列表/数组作为索引，支持选取非连续元素
fancy_result = arr[[0, 2, 4]]
print("\n1. 花式索引提取结果（索引0,2,4）：")
print(fancy_result)

# 3. 使用布尔索引提取所有大于20的元素
# 布尔索引：通过布尔掩码筛选元素，True表示保留对应位置的元素
bool_mask = arr > 20
print("\n布尔掩码（大于20的元素标记为True）：")
print(bool_mask)
bool_result = arr[bool_mask]
print("\n2. 布尔索引提取结果（大于20的元素）：")
print(bool_result)

原数组：
[10 15 20 25 30 35]

1. 花式索引提取结果（索引0,2,4）：
[10 20 30]

布尔掩码（大于20的元素标记为True）：
[False False False  True  True  True]

2. 布尔索引提取结果（大于20的元素）：
[25 30 35]


### 练习题 5：数组运算与广播机制



**题目：** 创建一个形状为 `(3, 4)` 的全 0 数组（使用 `zeros()` 函数）和一个一维数组 `arr_b = np.array([1, 2, 3, 4])` 。利用 NumPy 的广播机制，将这两个数组相加并打印出结果 。

In [5]:
import numpy as np

# 1. 创建形状为(3,4)的全0数组（默认float64类型）
arr_a = np.zeros((3, 4))
print("全0数组 arr_a (shape: {}):".format(arr_a.shape))
print(arr_a)

# 2. 创建题目指定的一维数组
arr_b = np.array([1, 2, 3, 4])
print("\n一维数组 arr_b (shape: {}):".format(arr_b.shape))
print(arr_b)

# 3. 利用广播机制进行数组相加
result = arr_a + arr_b
print("\n广播相加后的结果 (shape: {}):".format(result.shape))
print(result)

全0数组 arr_a (shape: (3, 4)):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

一维数组 arr_b (shape: (4,)):
[1 2 3 4]

广播相加后的结果 (shape: (3, 4)):
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### 练习题 6：通用函数的应用

**题目：** 给定数组 `x = np.array([1, 4, 9, 16])` 和 `y = np.array([2, 1, 4, 5])`。

1. 使用一元通用函数 `np.sqrt()` 计算数组 `x` 中每个元素的平方根 。  

   

   

2. 将得到的平方根数组与数组 `y` 结合，使用二元通用函数 `np.maximum()` 找出对应位置上的最大值 。 

In [6]:
import numpy as np

# 1. 创建题目指定的两个数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
print("原数组 x：", x)
print("原数组 y：", y)

# 2. 使用一元通用函数np.sqrt()计算x中每个元素的平方根
x_sqrt = np.sqrt(x)
print("\n1. 数组x的平方根结果：", x_sqrt)

# 3. 使用二元通用函数np.maximum()找出对应位置的最大值
result = np.maximum(x_sqrt, y)
print("\n2. 对应位置最大值结果：", result)

原数组 x： [ 1  4  9 16]
原数组 y： [2 1 4 5]

1. 数组x的平方根结果： [1. 2. 3. 4.]

2. 对应位置最大值结果： [2. 2. 4. 5.]


### 练习题 7：数组的转置



**题目：** 创建一个形状为 `(2, 3, 4)` 的三维数组 `arr = np.arange(24).reshape((2, 3, 4))` 。使用 `transpose()` 方法将该数组的轴顺序转换为 `(1, 0, 2)`，并打印转换后新数组的形状（`shape`） 。  


In [7]:
import numpy as np

# 1. 创建形状为(2, 3, 4)的三维数组
arr = np.arange(24).reshape((2, 3, 4))
print("原数组形状：", arr.shape)
print("原数组：")
print(arr)

# 2. 使用transpose()方法将轴顺序转换为(1, 0, 2)
arr_transposed = arr.transpose((1, 0, 2))
print("\n转置后数组形状：", arr_transposed.shape)
print("转置后数组：")
print(arr_transposed)

原数组形状： (2, 3, 4)
原数组：
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

转置后数组形状： (3, 2, 4)
转置后数组：
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


### 练习题 8：条件逻辑运算



**题目：** 给出两个一维数组 `arr_x = np.array([1, 5, 7])`，`arr_y = np.array([2, 6, 8])` 以及一个布尔条件数组 `arr_con = np.array([True, False, True])` 。请使用 `np.where()` 函数，当条件为 `True` 时取 `arr_x` 中的对应元素，当条件为 `False` 时取 `arr_y` 中的对应元素 。 

In [8]:
import numpy as np

# 1. 创建题目指定的三个数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

print("原数组 arr_x:", arr_x)
print("原数组 arr_y:", arr_y)
print("条件数组 arr_con:", arr_con)

# 2. 使用np.where()进行条件选择
# 语法：np.where(condition, x, y) → True取x，False取y
result = np.where(arr_con, arr_x, arr_y)
print("\n条件选择结果:", result)

原数组 arr_x: [1 5 7]
原数组 arr_y: [2 6 8]
条件数组 arr_con: [ True False  True]

条件选择结果: [1 6 7]


## 练习题 9：统计运算与排序



**题目：** 创建二维数组 `arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])` 。  



1. 使用统计方法计算该数组所有元素的算术平均值（`mean()`）。  

   

   

2. 使用 `sort()` 方法对该数组沿着 `axis=0` 的方向（按列顺序从小到大）进行排序，并打印排序后的结果 。  


In [9]:
import numpy as np

# 1. 创建题目指定的二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
print("原数组：")
print(arr)

# 2. 计算所有元素的算术平均值
mean_val = arr.mean()
print(f"\n1. 数组所有元素的算术平均值：{mean_val}")

# 3. 沿着axis=0（按列）从小到大排序（原地排序）
arr.sort(axis=0)
print("\n2. 按列（axis=0）排序后的数组：")
print(arr)

原数组：
[[6 2 7]
 [3 6 2]
 [4 3 2]]

1. 数组所有元素的算术平均值：3.888888888888889

2. 按列（axis=0）排序后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


### 练习题 10：随机数生成与矩阵点积



**题目：** 1. 设置随机数种子为 `10`（使用 `np.random.seed()` 保证每次生成的随机数一致）。 2. 使用随机数模块生成两个形状为 `(2, 2)` 且服从 [0, 1) 均匀分布的随机矩阵 A 和 B（使用 `np.random.rand()`）。 3. 使用线性代数模块的 `dot()` 方法计算矩阵 A 和矩阵 B 的点积 。

In [10]:
import numpy as np

# 1. 设置随机数种子为10，保证每次运行生成的随机数完全一致
np.random.seed(10)

# 2. 生成两个形状为(2,2)且服从[0,1)均匀分布的随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

print("随机矩阵 A (shape: {}):".format(A.shape))
print(A)
print("\n随机矩阵 B (shape: {}):".format(B.shape))
print(B)

# 3. 使用np.dot()计算两个矩阵的点积（矩阵乘法）
dot_result = np.dot(A, B)
print("\n矩阵 A 和 B 的点积结果 (shape: {}):".format(dot_result.shape))
print(dot_result)

随机矩阵 A (shape: (2, 2)):
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

随机矩阵 B (shape: (2, 2)):
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵 A 和 B 的点积结果 (shape: (2, 2)):
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
